### ISSUE TITLE
Interleaving rootfs across NUMA domains

### ISSUE THREAD

**Issue by rdahringer** [warewulf/warewulf#1006]
### Summary

On systems with a large number of NUMA domains, the ability to have the initramfs interleaved across the NUMA domains to have a balanced available memory.

Document the use of noefi, tmpfs, and dracut to avoid this issue.

Also, investigate whether noefi changes the output of acpidump or dmidecode.

### Rationale

Currently, when the initramfs loads, it is put into the highest numbered NUMA domain.  Once this memory is "Freed" by the kernel, a hole in that NUMA doman exists that is the size of the initramfs:
$ numactl -H | grep size
node 0 size: 14305 MB
node 1 size: 16585 MB
node 2 size: 16631 MB
node 3 size: 16631 MB
node 4 size: 16100 MB
node 5 size: 16127 MB
node 6 size: 16127 MB
node 7 size: 7113 MB

Memory bound workloads that are NUMA aware will not be able to use more than 7GB of RAM across all domains, and will affect performance.

### Description

To have the initramfs interleaved across NUMA domains to minimize the impact of the OS residing in memory. Other alternatives include network booting only the kernel with the OS on disk, or minimizing the OS to such an extent that most of it will reside on a local disk or a read-only NFS share.

### Additional information

Discussion of this topic is on the slack channel, originally posted by [Richard Dahringer](https://hpcng.slack.com/archives/C0YKGK6D6/p1701724205106959)

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by anderbubble** [comment]
With this in place, it seems that the OS is interleaved properly yet something is still taking additional space (in the size of the whole image) from a single numa node. Whereas before the OS was in that node but nowhere else. We suspect that the os is loaded into the single node during boot then not freed properly after it is copied to tmpfs.

This appears to be because `wwinit/init` requires that we start with a `ramfs`, which can't free memory.

> Rootfs is a special instance of ramfs (or tmpfs, if that’s enabled), which is always present in 2.6 systems. You can’t unmount rootfs for approximately the same reason you can’t kill the init process; rather than having special code to check for and handle an empty list, it’s smaller and simpler for the kernel to just make sure certain lists can’t become empty.

https://docs.kernel.org/filesystems/ramfs-rootfs-initramfs.html

`wwinit/init` implies that you can’t switch_root from a tmpfs. But I suspect it may be wrong.

**Comment by anderbubble** [comment]
Taking a note from a (partially remembered) Slack community conversation: adding `noefi` to the kernel command line appeared to alleviate the issue of issue of the original ramdisk not being freed. Our theory is that Linux keeping these runtime services loaded prevented efi from de-allocating the memory from the initial ramdisk.

**Comment by anderbubble** [comment]
Done in #1396.
