### ISSUE TITLE
tracking changes on overlays,profiles...

### ISSUE THREAD

**Issue by henkela** [warewulf/warewulf#1062]
### Summary

Hi,
have you considered adding a tracking of changes or automatic versioning of files in overlays and profiles and even config files. I had a look a some of the go-files and it seemed to me that adding automatic adds and commits after file changes using a go gitmodule not too complicated. 

### Rationale

If several admins work on overlays and profiles it may change subtle (or not so subtle) configurations, which is hard to track down if for example one of the files in wwinit was changed. Of course, this could be managed by setting up a group policy on change management. However, it wouldn't prevent mistakes. But tracking the changes would allow for a rollback in case of unwanted or accidental file changes. 

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by griznog** [comment]
I keep my overlays and /etc/warewulf as git repos but handle commits manually. The idea of integrating revision control has been discussed before in the developer meeting, but it's very much not a one-size-fits all problem. For instance it'd need to be flexible enough to allow the admin to choose the revision control system as especially overlays might need to integrate with some other configuration tool(s) or CI/CD infrastructure a site is using. 

Rather than revision control direct integration, I think I'd rather see configurable hooks for `wwctl` like `[pre|post]-overlay-build` and `[pre|post]-overlay-edit` and to allow each site to specify their own script/tools to run, which could handle any revision control or other needs.

**Comment by henkela** [comment]
You are right. There are too many ways to get this done which makes it impossible to implement "the best solution". 
I like the idea of the hooks and would vote for having hooks for profile edit as well.
