### ISSUE TITLE
containers don't get built at import

### ISSUE THREAD

**Issue by mslacken** [warewulf/warewulf#1128]
Containers don't get build if the SyncUid command fails. In 4.4.0 the container image still gets build. We should restore the old behavior.

**Comment by anderbubble** [comment]
@mslacken does it build if you specify `wwctl container import --build`?

**Comment by mslacken** [comment]
Did not check for parameters, yet.

**Comment by anderbubble** [comment]
@mslacken I don't know why the `--build` option was there before; it doesn't appear that it did anything.

Previously the behavior was to build if syncuser didn't have any complaints but to not build if it did.

Now the current behavior is to never build automatically, but to build if `--build` is specified.

Do we need to change this behavior? Personally, I think the new behavior is less surprising; but it wasn't necessarily intentional.
