### ISSUE TITLE
Build Fails: cannot find package "." in...

### ISSUE THREAD

**Issue by dhelgerson** [warewulf/warewulf#1188]
### Steps to reproduce

make all

### Error message

GOOS=linux go build -mod vendor -tags "containers_image_openpgp containers_image_ostree" -o wwctl cmd/wwctl/main.go
internal/pkg/util/util.go:8:2: cannot find package "." in:
	/home/admin/warewulf-4.5.0/vendor/io/fs
internal/pkg/config/root.go:12:2: cannot find package "." in:
	/home/admin/warewulf-4.5.0/vendor/net/netip
make: *** [Makefile:37: wwctl] Error 1

### Information on your system

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Architechture: aarch64

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@dhelgerson thanks for getting in touch.

We are definitely able to build on Rocky and Suse, but I haven't tried to build on Debian myself. If I get a chance I'll check it out and let you know if I find anything; but you might try `make vendor` (or `go mod vendor` and `go mod tidy`) first. I'd expect that to be automatic, but maybe it's not getting triggered for you for some reason.

**Comment by dhelgerson** [comment]
trying those commands revealed that the debian repository version of go is 1.15 which was causing problems. I installed the tarball from go's installation instructions and it worked

**Comment by anderbubble** [comment]
Thanks for bringing this to our attention. I looked into backports for oldstable (Debian 11) and stable (Debian 12) and _both_ currently only go up to 1.19; but Warewulf recently moved to 1.20. As you indicated, this isn't necessarily a huge problem right now, because can install and updated golang from upstream; but we have been thinking of / moving toward providing Debian packages. We _might_ need to move back to 1.19 to do that.

@JasonYangShadow and @mslacken I'm going to close this issue out, but I'll add this topic to our next TSC agenda.
