### ISSUE TITLE
Please implement a 'livesync' mechanism

### ISSUE THREAD

**Issue by frx-wintermute** [warewulf/warewulf#1409]
### Summary

Hi,
as discussed in #1405, warewulf4 lacks a mechanism that allows the cluster administrator to live-update running compute nodes, whenever their corresponding container (VNFS image) has been modifed (for instance, because security or other upgrades have been performed within the container).

Please implement this mechanism in a command named ```wwctl container livesync CONTAINER [LIST_OF_NODES]``` or, perhaps, in a dedicated tool such as ```wwlivesync CONTAINER [LIST_OF_NODES]```

### Rationale

I am convinced that this feature is a must-have for a provisioning system such as warewulf4.

In typical HPC clusters, a lot of users launch long-running jobs (usually through a resource manager, such as Slurm) and the compute nodes are almost always busy executing those jobs. It is already hard to find the appropriate time to reboot compute nodes for the occasional kernel upgrade: in all other situations, compute nodes should be kept up and running in order to maximize the cluster availability to users.

On the other hand, a cluster administrator has to perform system upgrades on the head node, as well as on the container(s) (VNFS image(s)) associated with the compute nodes. These upgrades (for security or otherwise) have to be performed frequently (even on a daily basis). Having to reboot compute nodes with this frequency clashes with the above-mentioned HPC needs.

For these reasons, I believe that a 'livesync' mechanism is of paramount importance.

### Description

This feature does not look excessively difficult to implement.

It seems to basically be an ```rsync``` invocation from the container rootfs ```/usr/local/var/warewulf/chroots/CONTAINER/rootfs``` to the live root filesystem of each running node (among the nodes which are associated with that container). This ```rsync``` invocation should have a configurable include/exclude file ```wwlivesync_skip.conf``` (where the administrator may tweak the directories/files to be excluded, such as ```/proc```, ```/sys```, ```/run```, ```/home```, and so forth). This file should be passed to ```rsync``` with the ```--include-from=``` option.

### Additional information

Other provisioning systems used to have this feature: PERCEUS had the ```perceus vnfs livesync``` command (implemented through a script that invokes ```rsync```). Even warewulf3 had the ```wwlivesync``` command (I found it in the [documentation]).

[documentation]: <https://warewulf.lbl.gov/recipes/perceus-migration.html>

It's time for warewulf4 to implement this feature, too!   :-)

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by anderbubble** [comment]
@frx-wintermute thank you for the feature request.

I have added this to the agenda for an upcoming TSC meeting.

**Comment by frx-wintermute** [comment]
> @frx-wintermute thank you for the feature request.
> 
> I have added this to the agenda for an upcoming TSC meeting.

Thank you so much, this is really appreciated.

By the way, I forgot to note that, after the ```rsync``` invocation that live-updates a running compute node, there will probably be the need to re-apply wwinit overlays to the live-updated node...

**Comment by frx-wintermute** [comment]
Hi, I prepared a script which implements the tool ```wwlivesync```.

The attached [livesync_script.tar.gz](https://github.com/user-attachments/files/17446792/livesync_script.tar.gz) includes the script, along with an example ```wwlivesync_skip.conf``` configuration file (which the sysadmin should customize for each container and include it into the container itself).

I tested this script a few times and it seems to work correctly.

The script may be invoked as follows.

Live-update all running compute nodes associated with the container named 'debian-trixie-run':

```console
# wwlivesync debian-trixie-run
```

Live-update some specified compute nodes with the current content of the contaner named 'rocky-greenobsidian-run':

```console
# wwlivesync rocky-greenobsidian-run 'cnode[001,024-035]'
```

The node list syntax is the one supported by ```pdsh``` (which has to be installed and usable to reach nodes via SSH).


Please include this script (along with the example configuration file) into Warewulf4.

Thanks for reading so far!

**Comment by griznog** [comment]
Once you get into the area of complex overlays that manage installed services, `livesync` as a way to keep live nodes in sync is an inherently flawed process. At the very least it's potentially applying the result of an `apt` or `dnf` installed/updated package that runs scripts at install time that assume they will run on the node where the package is installed and associated service(s) running and also potentially overwrites changes made by overlays. Consider a case where the node image has an unmodified config file that just gets updated but running nodes have an overlay provided config so that if the package installed on a running node, the new file would be `configfile.rpmnew` instead of overwriting the deployed/running config as a `livesync` would do. 

I don't think adding it to warewulf as a supported/integrated feature is a good idea because it'll add the support burden of testing, debugging, etc., something that is very site dependent and has pretty much infinite corner case potential. This is the kind of thing that should be done locally by the admin to incorporate the nuances of any given site, for example I'd approach this by only ever modifying a node image via package installs/updates/removals and do that with a wrapper that did the equivalent of (pseudocode)

```
wwctl container exec mycontainer dnf -y install somepackage && \
  clush -w @allnodeswiththisimage dnf -y install somepackage
```

However, having said that, I have my own collection of local hacks that also fit into this category of things that I use and maybe aren't for everyone but have merit as ideas or workarounds and it would be nice to have a wiki, `contribs` or separate repo or some other organized way for people to contribute and document ideas, recipes and hacks they use in their WW environments.

**Comment by frx-wintermute** [comment]
> Once you get into the area of complex overlays that manage installed services, `livesync` as a way to keep live nodes in sync is an inherently flawed process. At the very least it's potentially applying the result of an `apt` or `dnf` installed/updated package that runs scripts at install time that assume they will run on the node where the package is installed and associated service(s) running and also potentially overwrites changes made by overlays. Consider a case where the node image has an unmodified config file that just gets updated but running nodes have an overlay provided config so that if the package installed on a running node, the new file would be `configfile.rpmnew` instead of overwriting the deployed/running config as a `livesync` would do.

I see what you mean and I cannot say that there will never be cases where some by-hand after-sync fixing may be needed, but the ```wwlivesync_skip.conf``` is there to minimize the number of such cases.
First off, I excluded all files that are provided with overlays. Some other corner cases may happen, and, if all else fails, one can always decide that it's time to reboot the compute nodes: but this is still far better than having to *always* reboot the compute nodes, after each and every container update!

Moreover, if there's a way to force a running node to re-apply its system overlays, the ```wwlivesync``` could be enhanced to also issue the appropriate warewulf4 command to this effect...
Is there a way?

> 
> I don't think adding it to warewulf as a supported/integrated feature is a good idea because it'll add the support burden of testing, debugging, etc., something that is very site dependent

I think the ```wwlivesync_skip.conf``` configuration file allows the cluster admin to tweak the behavior for each container.
And anyway, nobody is saying that an admin is forced to use (or to always use) ```wwlivesync```, even if he/she doesn't like it (or if he/she thinks that a given container update requires a reboot).

> and has pretty much infinite corner case potential. This is the kind of thing that should be done locally by the admin to incorporate the nuances of any given site, for example I'd approach this by only ever modifying a node image via package installs/updates/removals and do that with a wrapper that did the equivalent of (pseudocode)
> 
> ```
> wwctl container exec mycontainer dnf -y install somepackage && \
>   clush -w @allnodeswiththisimage dnf -y install somepackage
> ```

Well, this distributes the package installation/upgrade to each compute node: one of the key advantages of warewulf4 (or other similar provisioning systems) seems to be thus lost. The advantage is the administration centralization: instead of having to upgrade N compute nodes, you just upgrade a few containers. But your wrapper implies that you upgrade a few containers + N compute nodes, which looks even more work to do...

> 
> However, having said that, I have my own collection of local hacks that also fit into this category of things that I use and maybe aren't for everyone but have merit as ideas or workarounds and it would be nice to have a wiki, `contribs` or separate repo or some other organized way for people to contribute and document ideas, recipes and hacks they use in their WW environments.

I would still prefer to see my script included in the official warewulf4 git repository...

**Comment by griznog** [comment]
My response was in the context of my own use of Warewulf, which I didn't describe and which addresses some of your points.

1. I only have one node image per Linux distro/version.
2. Changes to node images are limited to only package installs/updates/removals.

With respect to my example of a wrapper that installs packages on the container and nodes using it, you suggest that is "more work", but in reality there's not much difference or possibly less work, from both processing power used to do it and admin effort. If I upgrade a node image and then livesync that to all nodes running the node image, then I've arguably done more work as I've had to
* `rsync` check every file on N nodes to do the equivalent of `dnf install` 
* maintain `wwlivesync_skip.conf` for each container, keeping track of all overlay files, including those that might be dynamcailly created, ownership, permissions, etc.
* follow up on nodes for anything that needed some script to run during the package install, service (re)started or whatever fine tuning.

One could also argue that doing any sort of livesync ignores THE key advantage of WW, which is using reboots to guarantee node state. Even in my environment where I live update nodes frequently and end up with node uptimes in the triple digits, the gold standard for node sanity is `scontrol reboot asap NODENAME`. 

The next way my use differs is that I don't use `wwclient` or treat system vs runtime overlays differently. I have (as of this moment) 83 overlays, many that manage or set up `systemd` services which on any change require `systemctl daemon-reload` and reload/restart of the affected service. That happens via a local wrapper that I use with `clush` to update individual overlays on nodes as needed rather than automatically pulling the merged runtime overlays on a schedule. Automatically pulling the runtime overlays en masse breaks pretty much as soon as you start using overlays for anything really interesting. 

Hopefully all the above helps make the point that this is very much a "season to taste" thing which does and should vary by admin and site and would be great to have in a separate location for people to reference or use as they wish, but WW itself should just provide the (simple, robust and reliable) framework that makes these things possible.

**Comment by anderbubble** [comment]
@frx-wintermute this was discussed in a recent steering committee meeting. At this time, we do not intend to add a function to synchronize a full image outside of the overlay system. There are just too many potential issues with services not restarting, accidentally overwriting unexpected files, re-writing binaries and scripts that are being executed, etc. This is why the system is designed to either capture variable files with runtime overlays or treat the image as static until the next reboot.

**Comment by anderbubble** [comment]
Worth noting: because the running system is writable, you can always deploy patches to the live system using standard system administration tools. One technique might be to build your image with ansible, and in such a way that you can run your playbooks either against the image or against the compute nodes. In this way, you could live-patch nodes if you must, but you can use the same configuration to build static / stateless images for the common case.
