### ISSUE TITLE
node matching pattern is incompatible to slurm and friends

### ISSUE THREAD

**Issue by mslacken** [warewulf/warewulf#167]
slurm and friends use for node ranges something like
```
node[02,10-12]
```
which expands to `node02,node10,node11,node12`
In contrast to this `wwctl node list node[02,10-12]` tries to expand `node[02,10-12]` to regexp which sometimes terribly goes wrong.
In mslacken@5184fd35b91801d46b3c24d92ac874834ed67444 I already tried to trim the input in such a way that e.g. `node[01-05]` would end up in `node[01-5]` bit this is still a regexp and not the wanted range.
Any comments?

**Comment by tcooper** [comment]
Hmm... Maybe because folks might have other tooling that expects `hostlist` like behavior for compound hostlists like...

"nodes 1 through 15 but not node 11"?

```
$ hostlist -d node-[1-15] node-11
node-[1-10,12-15]
````

Or, how about, "Give me the groupings of nodes in the rack that share the same leaf switch on my IB fabric?"

```
$ hostlist --chop=18 node-[01-72]
node-[01-18]
node-[19-36]
node-[37-54]
node-[55-72]
```

I mean, both can be made to work but I would argue the `hostlist` behavior is more common when dealing with nodes on an HPC system, especially when Slurm is used as the batch scheduler.

So much so that it might just be better to look for an install of `hostlist` and shell out to that from Golang if it's not completely reimplemented in Golang.
