### ISSUE TITLE
update quick-start 

### ISSUE THREAD

**Issue by rhenwood-arm** [warewulf/warewulf#401]
A number of changes have been landed that change the common operating behavior of Warewulf. These changes may not be reflected in the quick-start document https://warewulf.org/docs/quickstart/el8/

This ticket is about verifying the current quick-start and the accuracy of the current Warewulf Main branch.

**Comment by odidev** [comment]
Hi Team,  

I am working with WareWulf on the **AWS Graviton2 metal instance (ARM64) with RHEL booted**. 

I followed the [EL8 quickstart guide](https://warewulf.org/docs/quickstart/el8/) to install and run warewulf using the main branch.  

In Step-3, to [configure the controller](https://warewulf.org/docs/quickstart/el8/#configure-the-controller) - I copied the example configuration file in the quickstart guide at /etc/warewulf/warewulf.conf, filled the ipaddr (172.31.21.74) and netmask (255.255.240.0) with the eth0 inet address displayed by the command - `ifconfig`
Also, I edited the dhcp start and end range from 172.31.21.84 to 172.31.21.174. 

Kindly find my configuration file here: [warewulf_config.txt](https://github.com/hpcng/warewulf/files/8528748/warewulf_config.txt)
 

I am facing issues in configuring system services automatically, as DHCP service fails to start. Below are the error logs: 
~~~ 
$ sudo /usr/local/bin/wwctl configure --all 

Enabling and restarting the DHCP services 
Job for dhcpd.service failed because the control process exited with error code. 
See "systemctl status dhcpd.service" and "journalctl -xe" for details. 
[ERROR]      : failed to start: failed to run start cmd: exit status 1 
~~~ 

Kindly find the detailed error logs below: 
1. systemctl status dhcpd.service :  [warewulf_systemctl_logs.txt](https://github.com/hpcng/warewulf/files/8528761/warewulf_systemctl_logs.txt)

2. journalctl –xe :  [warewulf_journalctl_logs.txt](https://github.com/hpcng/warewulf/files/8528763/warewulf_journalctl_logs.txt)

**Comment by elguero** [comment]
What are the contents of `/etc/dhcp/dhcpd.conf`?

**Comment by odidev** [comment]
@elguero,  Thank you for the response. 

I realized that there is no dhcp configuration file present in my system, as you have mentioned - `/etc/dhcp/dhcpd.conf`, even after installing dhcp-server. 

I created a configuration file for dhcp (considering some examples online) and added below subnet information to it: 
`/etc/dhcp/dhcpd.conf:`
~~~ 
option domain-name "tecmint.lan"; 
option domain-name-servers ns1.tecmint.lan, ns2.tecmint.lan; 
default-lease-time 3600; 
max-lease-time 7200; 
authoritative; 

subnet 172.31.21.74 netmask 255.255.240.0 { 
        option routers                  172.31.21.75; 
        option subnet-mask              255.255.240.0; 
        option domain-search            "tecmint.lan"; 
        option domain-name-servers      172.31.21.75; 
        range   172.31.21.84   172.31.21.184; 
~~~ 

FYI - my private network IP is 172.31.21.74 and it’s netmask is 255.255.240.0. 

I again enabled and started the warewulf services, and faced issues in configuring system services, as dhcp service again failed to start. 

Journalctl logs do not show **subnet not found** error anymore. However, it seems that the dhcp configuration file has some issues. Below are the error logs with journalctl: 
~~~ 
Apr 22 09:21:31 ip-172-31-21-74.us-east-2.compute.internal dhcpd[8954]: /etc/dhcp/dhcpd.conf line 11: subnet 172.31.21.74 netmask 255.255.2> 
Apr 22 09:21:31 ip-172-31-21-74.us-east-2.compute.internal dhcpd[8954]: subnet 172.31.21.74 netmask 255.255.240.0 
Apr 22 09:21:31 ip-172-31-21-74.us-east-2.compute.internal dhcpd[8954]:                                         ^ 
Apr 22 09:21:31 ip-172-31-21-74.us-east-2.compute.internal dhcpd[8954]: Configuration file errors encountered -- exiting 
~~~

**Comment by elguero** [comment]
@odidev I would suggest opening a new issue for this with the pertinent information such as OS info.  Warewulf should be creating the dhcpd configuration file for you and managing that.  If that file was not created when running `wwctl configure --all` then that needs to be looked into.

Thanks

**Comment by odidev** [comment]
@elguero, Thanks for your feedback.  

I worked on the latest stable release **(v4.2.0) zip** and built and installed warewulf with it. I can successfully configure the system services automatically while executing `sudo wwctl configure --all`.  

I think there are some issues with the main branch. Even the releases with rc* tags behaving exactly like the main branch.

**Comment by rhenwood-arm** [comment]
@odidev - i attended the call today, it seems Main should be close to a release candidate. Can you start over with the quick-start instructions and see if DHCP starts correctly with the current Main branch?

**Comment by odidev** [comment]
The dhcp configuration issue in the main branch has been resolved after the commit <https://github.com/hpcng/warewulf/commit/fea148903c421daf99900b675f5db175620a3910> has been merged - FYI.
