### ISSUE TITLE
50-ipmi wwinit script hangs when ipmi password blank

### ISSUE THREAD

**Issue by NateCrawford** [warewulf/warewulf#638]
In Warewulf 3.x, a blank ipmi password would be replaced with a random string in the configuration for each node. In WW4, it appears that a blank password is passed to the node as-is. The current 50-ipmi script flags the password as undefined, but continues trying to set up the ipmi user. At least on the nodes I've tested, the script will wait indefinitely with:

IPMI command failed: Invalid data field in request
Password for user 2: _

  I think this check isn't working: https://github.com/hpcng/warewulf/blob/d99717f28802a683aea218829284fbdf9fcfb629/overlays/wwinit/warewulf/init.d/50-ipmi#L62-L64

**Comment by anderbubble** [comment]
@NateCrawford I think the behavior of attempting to set up a blank password may be acceptable as a bug; but can you clarify whether you'd consider the injection of a random password by default to be a preferred behavior for future enhancement?

I think my personal preference, not having experience with the previous behavior, would be to have a dedicated flag or sentinel value for requesting a random password; but I'd be interested to hear otherwise.

**Comment by mslacken** [comment]
If not password is given, the script should simply do nothing as then there is no clear intention what the user wants.
