### ISSUE TITLE
Merge NodeConf and NodeInfo

### ISSUE THREAD

**Issue by anderbubble** [warewulf/warewulf#916]
I think a lot of the complexity in Warewulf comes from the separation between `NodeConf` and `NodeInfo`, and having to keep these two datastores in sync. I suggest that they (and their children) should be merged into one `Node` data structure, and that the functionality currently present in `NodeInfo` should be handled on-demand by view-only functions.

**Comment by griznog** [comment]
I think this is an implied goal of https://github.com/hpcng/warewulf/issues/905, the actual nodes.conf contents would not have any data structure associated with them and be kept in sync between memory and disk, with any individual nodeinfo things being pulled out of that in a read-only fashion dynamically as-needed. 

A side effect here  is getting the code path for merging nodes with assigned nodeprofiles into a separate place where it can be improved to do a better job of merging these. I think with this model it only has to merge into a read-only structure (which could still be a map without any formal data structure to it), so that merging logic can be as complex as needed. Any commands that update the config would work directly in the flatter/unmerged in-memory config then be flushed to disk.
